feat(argocd): handle complex object type for addon_config
The previous commit uses a complext object type to specify values for
a helm chart with multiple subcharts.

However this triggers Inconsistent conditional result types error like
following:

> Error: Inconsistent conditional result types
>   on .terraform/modules/eks.blueprints_kubernetes_addons/modules/kubernetes-addons/argocd/main.tf line 72, in resource "helm_release" "argocd_application":
>   72:       each.value.add_on_application ? var.addon_config : {}
>     ├────────────────
>     │ each.value.add_on_application is true
>     │ var.addon_config is object with 10 attributes
>
> The true and false result expressions must have consistent types. The
> 'true' value includes object attribute "awsEfsCsiDriver", which is absent
> in the 'false' value.

To workaround the issue I had to encode & decode the line causing the issue.
It doesn't look pretty but I don't come up a better solution.